#server.servlet.context-path=/smartVehicle/
server.port=7080
spring.application.name=Smart Vehicle
# Database Configuration


# File upload size settings
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB


#spring.datasource.url=jdbc:mysql://localhost:3306/smartvehicle
#spring.datasource.username=admin
#spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Enable Spring JPA Repositories
spring.data.jpa.repositories.enabled=true

# Spring Security settings
smart_vehicle.app.jwtSecret= ======================smartvehicle=user===========================
smart_vehicle.app.jwtExpirationMs=86400000


# Logging
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework=ERROR
logging.level.com.smartvehicle=DEBUG
logging.level.com.twilio.rest.verify.v2=ERROR
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.name=logs/application.log



logging.level.org.apache.commons.net=DEBUG


ftp.remoteDir=/upload
ftp.buffer.size=65536
ftp.use.chmod=false
ftp.use.passive=false
ftp.timeout=2000
